### ISSUE TITLE
Create a help panel

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#11]
Add a panel that contains the list of keybindings with an explanation on what they do.

The panel would occupy on the whole screen, and its visibility would be toggled using a key (such as `h`).

**Comment by Siddhi-agg** [comment]
Hey, I have set up this project on my local machine as required. 
Screenshot:
![Screenshot 2024-03-06 201645](https://github.com/panglesd/diffcessible/assets/101979598/80562663-34d2-45fd-8da8-8f006de7cc48)
Can I be assigned this issue?

**Comment by panglesd** [comment]
Yes! You are now assigned this issue.

Do let us know when you are blocked and need assistance on this one!

**Comment by Siddhi-agg** [comment]
@panglesd I have read and got an understanding of the code in the /bin and /lib  directory. I am a bit unclear about what the help panel should include. Should it just have the explanation of the keyboard key functions like n, p or should it also contain the information about the diffcessible command its arguments?
Can you please elaborate on that?

**Comment by panglesd** [comment]
Sure!

The help panel will only contain a small explanation of the layout of what you can find on the screen, and a list of key-bindings.

Currently, the keybindings are only `n`, `p`, `q` and soon `h`, so it might feel a little bit empty. However, we plan to have  `UpArrow`/`DownArrow` and `j`, `k` to scroll, some key to alternate between "side-by-side" diff and normal diff, maybe a way to navigate hunks (instead of operations...).

Having the help panel already implemented will simplify the addition of help for those new key-bindings!

**Comment by Siddhi-agg** [comment]
I have tried implementing a logic for a toggle help panel which goes like:
![Screenshot 2024-03-08 043811](https://github.com/panglesd/diffcessible/assets/101979598/57c8feeb-0756-4c1a-b0dc-28ffa55b04d7)

After testing it, I found the toggling function was not working. Can you suggest me why that may be happening?

**Comment by panglesd** [comment]
It's a good start! But there are some small issues.

Let me explain again some of concepts of `Lwd`:
- `Lwd.var` is a variable: it contains some data (that you can see with `Lwd.peek` and modify with `Lwd.set`)
- The `'a Lwd.t` type is the type of a `'a` that might change over time
- The `Lwd.get` function allows you to turn an lwd variable into a value that might change over time! (It changes when the value of the variable change)
- The `Lwd.bind` allows to take values that changes over time, and create a new value that changes time, with a regular function. This is mostly used through the `let$` syntax.
- A UI element that changes over time will have the changes reflected in the terminal. So the idea is to have a few Lwd variables, and build the UI from them. Whenever they change, the changes in the UI will be reflected in the terminal.

Some additional (arguably not easy to read) documentation for lwd is available [in its homepage](https://github.com/let-def/lwd).

Hope this helps! Let me know if you need more assistance. But since you already have some code written, it would be better to open a PR, even unfinished: that's much better to read and comment the code than a screenshot or copy-pasted unsyntaxhighlighted code...

**Comment by Siddhi-agg** [comment]
@panglesd Thanks for explaining these concepts. I understood why even after pressing h key, the help panel isn't being displayed and now I am working on implementing how to use Lwd.get to check if the help panel should be visible.
I am currently reading the documentation for Lwd and also watching some video tutorials for getting a better understanding of the code.
