### ISSUE TITLE
Use keyboard arrows for scrolling

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#14]
Currently, it's only possible to scroll the visible part of the hunk via the mouse. This isn't a very accessible interface.

The goal of this task is to add the following key-bindings:
- `up`: Scrolls toward the top.
- `down`: Scrolls toward the bottom.

Scrolling is implemented by [Nottui_widgets](https://ocaml.org/p/nottui/latest/doc/Nottui_widgets/index.html). We are currently using `W.scrollbox` but we'd need to switch to `W.vscroll_area` to have the keybindings above.

`W.scrollbox` is a nottui widget that implements scrolling using the mouse. The "scrolling state" is hidden in the widget and we cannot add any shortcut to modify it. So, we cannot use this widget for our purpose.
`W.vscroll_area` is a widget that implements (vertical) scrolling using the keyboard.

So, solving this task requires to switch to `W.vscroll_area`. This function takes as input a `scroll_state` and a function to modify the scroll state, that need to be create. It will be handy to be able to modify the scroll state from the outside of the function to add new keybindings.

**Comment by nandini584** [comment]
heyy, this is nandini arora, i am an outreachy applicant and i want to work on this issue...
![Uploading Screenshot from 2024-03-06 20-36-44.png…]()

**Comment by panglesd** [comment]
This issue is assigned to you @nandini584 !

**Comment by nandini584** [comment]
I am facing certain problems while solving this issue, I understood the fact that a variable scroll_state is to be formed, then change_scroll_state, but how shall i implement W.vscroll_area, its a bit confusing, although i have gone through the documentation.

**Comment by panglesd** [comment]
The function `scroll_area` is already written: it is part of the `Nottui_widget` module (at the top of the file, we define `W` as an alias to `Nottui_widget` to avoid writing the full module name each time).

The documentation for this function is available here: https://ocaml.org/p/nottui/latest/doc/Nottui_widgets/index.html#val-vscroll_area
I agree that we cannot really say "documentation": there is no explanation, but actually the interface (the type of the function) is already telling us a lot on how it works!

I hope this information will unblock you! I can provide a little more guidance if you are still blocked, after trying for some time.

**Comment by nandini584** [comment]
Thanks for your guidance, i will give it a shot.

**Comment by Siddhi-agg** [comment]
@nandini584 Are  you still working on this? If not, I would like to work on this issue.

Also if you are stuck somewhere, I would love to work along with you.

**Comment by nandini584** [comment]
@Siddhi-agg hey, I am working on this and will raise a pr by evening. Thanks..

**Comment by nandini584** [comment]
Sure go for it.

**Comment by Siddhi-agg** [comment]
@nandini584 Okay, then I will start working on it!
@Julow Can this issue be assigned to me?

**Comment by Julow** [comment]
@Siddhi-agg This issue is assigned to you.
