### ISSUE TITLE
Compute and display number of hunks in the status bar.

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#18]
It would be nice to display the number of hunks for the current operation, in the top status bar.

For instance:

```
--- a/path/to/file
+++ b/path/to/file
```
could become:
```
--- a/path/to/file
+++ b/path/to/file
7 hunks
```

**Comment by yokurang** [comment]
thanks @panglesd ! I think https://github.com/panglesd/diffcessible/issues/4 is a good go for me. Thank you for asking !

**Comment by yokurang** [comment]
Hi @panglesd, I just finished a PR for https://github.com/panglesd/diffcessible/issues/4 and would like to get back to this one if possible the PR is ok. Is ok if I reserve this issue? On another note, this issue also seems similar to https://github.com/panglesd/diffcessible/issues/19.

**Comment by Dezzy12** [comment]
Hello @Julow, Can I get this issue?

**Comment by panglesd** [comment]
Hello @Dezzy12 !

In order to make sure not to block issues for too long, we require applicants to submit a screenshot of the help page of the tool before assigning them an issue, ensuring that they are able to build the project.

Once that is done, I'll be happy to assign you the issue!

**Comment by iAlexeze** [comment]
Hello @panglesd 
I'd like to be assigned this issue.

Attached is my setup ready to take it on.

![Screenshot 2024-03-06 113909](https://github.com/panglesd/diffcessible/assets/126210538/0a2c60e0-2455-41d5-9480-6d512125f3b7)

**Comment by iAlexeze** [comment]
Thank you.

**Comment by panglesd** [comment]
@iAlexeze let you be assigned to this issue!

@Dezzy12 although you asked earlier to be assigned to this issue, we believe that now that you have completed a good first issue, you should pick a "medium issue". We will add more medium issues soon!

**Comment by iAlexeze** [comment]
I have made a draft of implementation on this issue, and submitted a pull request.
Kindly review @panglesd.
