### ISSUE TITLE
A more representative example file

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#28]
The file `diff.example` is nice for easily and quickly trying out the program but is not enough for testing it.

We need a new diff file that contains:

- All the different operations (for example, to test https://github.com/panglesd/diffcessible/pull/27)
- A hunk with only deleted lines
- A hunk with only added lines
- A hunk with both.

Ideally, this file would be generated by first crafting two directories with slightly different files in them and running on them `git diff --no-index`.

**Comment by Julow** [comment]
This issue is assigned to @Dezzy12

**Comment by Dezzy12** [comment]
@Julow , could you please shed some more light on how I can approach this task?

**Comment by Dezzy12** [comment]
> We need a new diff file that contains:

To be clear am I to add a new diff file or replace the existing `diff.example`

**Comment by Julow** [comment]
I think you can replace the existing `diff.example`. Perhaps also rename it `example.diff`, to more easily identify it.
