### ISSUE TITLE
Add CI testing using Github Actions

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#37]
The OCaml community has the awesome [ocaml-ci](https://github.com/ocurrent/ocaml-ci) but for some reason we cannot enable it on this project until next week.

In the meantime, it would be useful to have a CI that does the following:

- Setup an OCaml environment with [setup-ocaml](https://github.com/ocaml/setup-ocaml)
- Checkout the project source code.
- Install the project dependencies with `opam install --deps-only -t -y .`
- Run the tests with `dune runtest`.
- Check formatting with `dune build @fmt`.

This is a medium issue.

**Comment by maha-sachin** [comment]
@Julow  Can you help to assign this issue?

**Comment by maha-sachin** [comment]
@Julow, Thank you for assigning me this issue Add CI testing using GitHub Actions #37, I'll start working on it right away and keep you updated on my progress

**Comment by maha-sachin** [comment]
@Julow, When attempting to configure our CI workflow to run on the Windows environment (os: windows-latest) with the OCaml compiler version 4.14.0 (ocaml-compiler: "4.14.0"), I encountered an error during the setup process. Specifically, the error occurred while attempting to install dependencies, indicating a problem with resolving system dependencies for the diffcessible package.

```
Install system packages required by opam packages
  C:\Windows\system32\cmd.exe /D /S /C "D:\cygwin\wrapperbin\opam.cmd depext diffcessible"
  # Detecting depexts using vars: arch=x86_64, os=win32, os-distribution=cygwinports, os-family=windows
  [ERROR] No solution for diffcessible: The following dependencies couldn't be met:
            - diffcessible -> dune >= 3.11
                no matching version
  
  
  Command failed: opam list --readonly --external  "--resolve=diffcessible" returned 20
Error: The process 'D:\cygwin\wrapperbin\opam.cmd' failed with exit code 20
```

**Comment by Julow** [comment]
It seems that setup-ocaml on Windows uses an opam-repository (containing the definition of all the packages) that is too old and do not contain the version of `Dune` that we need.
This is to be fixed later, for now, let's continue without Windows in the CI.

**Comment by Julow** [comment]
Done!
