### ISSUE TITLE
example.diff do not show a file with several hunks

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#38]
The `example.diff` file, which is useful to quickly try out the project, do not contain a file that would show more than one hunk.
This is needed to test https://github.com/panglesd/diffcessible/pull/33

@iAlexeze Are you interested in fixing this issue, in a different PR?

**Comment by iAlexeze** [comment]
Yes I'd like to.

**Comment by Julow** [comment]
Fixed in #40 :)
