### ISSUE TITLE
Improve the `n` and `p` shortcuts

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#4]
The `n` and `p` shortcuts currently increment and decrement an integer. This integer is used as the index of the hunk to show on the screen.

This is a bad user experience as the integer can be incremented above the number of hunks, which has no visible effect except that the next `n` will also have no visible effect.

The `p` shortcuts should not set a value equal or above the number of hunks.
The `n` shortcuts should not set a negative value.

**Comment by panglesd** [comment]
Let this issue and #6 be assigned to you!

**Comment by panglesd** [comment]
Fixed by #26 !
