### ISSUE TITLE
Add keybinding to scroll to the top

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#46]
#36 has added the ability to scroll.

It would be nice to have a keybinding to scroll back to the top of the displayed operation.

Feel free to ask for help or clarification when working on this issue!

**Comment by Siddhi-agg** [comment]
@panglesd Hey, I wanted to work on a new medium issue. All other issues have been assigned. @Julow mentioned that they would like to assign the issues related to keybindings to someone who hasn't worked with that yet. So I just wanted to let you know that I am available to work on any other issues. Please assign me when they become available.

**Comment by Julow** [comment]
Hi @Dezzy12, this issue is for you :) While implementing this issue, you might need to read the documentation of [the type `Lwd.var`](https://ocaml.org/p/lwd/latest/doc/Lwd/index.html#type-var) and the related functions.

**Comment by Dezzy12** [comment]
> Feel free to ask for help or clarification when working on this issue!

About this could I please get some more clarification of what is expected for this issue?

**Comment by Julow** [comment]
Currently, the state of the scroll (which part of the diff is visible on the screen) is handled by the `curr_scroll_state`, which is a `_ Lwd.var`.
You need to add a keybinding in `Ui.keyboard_area` that changes the scroll state to show the beginning of the diff.

You need to decide on which key to use. You might look at existing TUI programs to find a key that users might already be used to.
