### ISSUE TITLE
Show line numbers in diffs

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#50]
Showing line numbers in a diff file is tricky as each line can have a different number before and after the patch is applied.

See for example, this diff from the `example.diff` file:

```diff
diff --git a/bin/main.ml b/bin/main.ml
index e03c4a4..cb71f31 100644
--- a/bin/main.ml
+++ b/bin/main.ml
@@ -1,7 +1,9 @@
 open Diffcessible
 
 let main () =
-  Interactive_viewer.start ()
+  let s = In_channel.input_all In_channel.stdin in
+  let patch = Patch.to_diffs s in
+  Interactive_viewer.start patch
 
 open Cmdliner
 
````

The line numbers are start at `1` in both files, as indicated by the `@@` line, but then diverges due to there being more added lines than removed lines.
The line numbers are as follow:
```
1  1  open Diffcessible
2  2  
3  3  let main () =
4    -  Interactive_viewer.start ()
   4 +  let s = In_channel.input_all In_channel.stdin in
   5 +  let patch = Patch.to_diffs s in
   6 +  Interactive_viewer.start patch
5  7  
6  8  open Cmdliner
7  9  
```

**Comment by Siddhi-agg** [comment]
I would like to work on this @Julow. Please assign this to me.

**Comment by Julow** [comment]
Alright, this issue is assigned to you :)
