### ISSUE TITLE
Outreachy Application: How to provide a timeline for the project

### ISSUE THREAD

**Issue by yokurang** [panglesd/diffcessible#51]
Hi @Julow @panglesd,

I am currently writing my application for this project via the Outreachy portal, and one of the prompts asks us to work with you to provide a timeline of the work we plan to accomplish on the project and what tasks we will finish at each step. May I inquire how to best answer this question and which projects you feel are great to include for this? 

Thank you very much.

Best regards,
yokurang

**Comment by panglesd** [comment]
Hello @yokurang (and any applicant interested in submitting a project!)

Happy to know you are applying for this project!

The best is to contact us (@Julow and me, you should have our email address through the outreachy project) by email, with a rough draft of the timeline as you would imagine it. We can then work together on finalizing it before the deadline!

**Comment by maha-sachin** [comment]
> Hi @Julow @panglesd,
> 
> I am currently writing my application for this project via the Outreachy portal, and one of the prompts asks us to work with you to provide a timeline of the work we plan to accomplish on the project and what tasks we will finish at each step. May I inquire how to best answer this question and which projects you feel are great to include for this?
> 
> Thank you very much.
> 
> Best regards, yokurang

@panglesd @Julow, This will be very helpful as we complete the final application.

**Comment by panglesd** [comment]
Hello @maha-sachin,

As I said, the best is to send us a tentative timeline by email, and we will answer with feedback!

Here are some general comments:

> Writing a timeline is always a hard exercise, and in the end almost never happen to be correct (even for very experienced programmer, it seems)! However, it is a good way to show you have ideas on what to work on, and that you would be proactive during the internship.
>
> - So, try to be avoid generic terms (such as "Implement a feature" (without providing an example of feature), "Debugging", ...).
> - Try to show that you understood the main topic of this project: accessibility.
> - Schedule time for research/design (and if possible describe how you would approach this).
> - Show us what kind of things you are interested in! (Is it more the implementation of complicated features? The design of the UI?)

These are general comments, feel free to add your personal touch!

**Comment by maha-sachin** [comment]
> Hello @maha-sachin,
> 
> As I said, the best is to send us a tentative timeline by email, and we will answer with feedback!
> 
> Here are some general comments:
> 
> > Writing a timeline is always a hard exercise, and in the end almost never happen to be correct (even for very experienced programmer, it seems)! However, it is a good way to show you have ideas on what to work on, and that you would be proactive during the internship.
> > 
> > * So, try to be avoid generic terms (such as "Implement a feature" (without providing an example of feature), "Debugging", ...).
> > * Try to show that you understood the main topic of this project: accessibility.
> > * Schedule time for research/design (and if possible describe how you would approach this).
> > * Show us what kind of things you are interested in! (Is it more the implementation of complicated features? The design of the UI?)
> 
> These are general comments, feel free to add your personal touch!

@panglesd Thank you for providing these helpful guidelines. I will draft a tentative timeline following your recommendations and send it to you via email for you to review.

**Comment by yokurang** [comment]
Applications closed
