### ISSUE TITLE
More efficient datastructure for storing hunks

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#6]
Hunks are currently stored in a list and accessed using an index. This operation have to iterate the list from the beginning to reach the desired hunk. Which is slow when looking at the end of a very large diff.

More efficient datastructures for this are: Array or Zipper.

**Comment by panglesd** [comment]
@yokurang is assigned this issue.

Let me just add a link to a good resource on Zippers: https://pavpanchekha.com/blog/zippers/huet.html
