### ISSUE TITLE
Add a side-by-side display of the diff

### ISSUE THREAD

**Issue by panglesd** [panglesd/diffcessible#8]
Reading diff side-by-side can be very useful:

![image](https://github.com/panglesd/diffcessible/assets/34110029/ca8df1df-b05b-4013-bbef-b5fee6f4bde3)

It would be nice to be able to switch from "normal" to "side-by-side" view by the press of a key.

**Comment by jatinder14** [comment]
please assign this issue to me @panglesd

**Comment by panglesd** [comment]
Hello @jatinder14, and thanks for offering your contribution!

In order to make sure not to block issues for too long, we require applicants to submit a screenshot of the help page of the tool before assigning them an issue, ensuring that they are able to build the project.

Moreover, this issue is labeled as "Medium issue" in #20, and could even be labelled medium-hard in my opinion. So I would advise you to start with a good first issue!

**Comment by panglesd** [comment]
Let this issue be assigned to @yokurang!

**Comment by panglesd** [comment]
@yokurang could you comment something on the thread (any message is fine)? I unfortunately [can't assign you](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) otherwise...

Having issues assigned helps to see which ones are free in the list of issues!

**Comment by yokurang** [comment]
I'd like to take this issue please! Thank you @panglesd
