### ISSUE TITLE
Test for the interface

### ISSUE THREAD

**Issue by Julow** [panglesd/diffcessible#9]
A new entry point in the `Interactive_viewer` library should be added, which allows to:
- Run the UI in a dummy terminal not connected to a real terminal of a fixed size.
- Send a sequence of predefined events.
- Print the last frame.

This can then be wrapped in a binary and called from a cram test.

**Comment by Shedrack-Sunday** [comment]
Hello @panglesd , I can't seem to find a first issue. Please can you assign this to me? I'll drop the screenshot of the helper page before the end of today. Thank you

**Comment by panglesd** [comment]
Hello @Shedrack-Sunday !

We will be adding new first issues soon! Also, we won't assign an issue before the screenshot. Hopefully when you have the screenshot, there will be new issues available!

Sorry about that...

**Comment by Dezzy12** [comment]
I think I might have an idea on what to do here, please can this issue be assigned to me?

**Comment by panglesd** [comment]
Since you already have PRs merged, let this medium issue be assigned to you @Dezzy12 !

**Comment by Julow** [comment]
> Run the UI in a dummy terminal not connected to a real terminal of a fixed size.

For clarity, by "dummy terminal" I'm not necessary talking about [creating a `Term.t`](https://ocaml.org/p/notty/latest/doc/Notty_unix/Term/index.html#val-create) of the library notty. This could be a good solution but I think getting the final image might be hard.

The `output` file descriptor can perhaps be opened from `/dev/null`. The `input` file descriptor requires more work as we need to write into it. See the [Unix](https://v2.ocaml.org/releases/5.1/api/Unix.html) module of the standard library.

An other solution is to write a different version of `Ui_loop.run`, defined in `vendor/lwd/lib/nottui/nottui.ml`, that do not use a `Term` but instead remember the last image using a `ref`. This means comming up with an implementation of `Term.pending` and `Term.event` that do not read a file descriptor but instead use a predefined list of events.

**Comment by Dezzy12** [comment]
Hello @panglesd, @Julow 

I'm currently facing difficulties in proceeding with the assigned task of adding a new entry point to the Interactive_viewer library. To start, I created a `dummy_terminal.ml` file where I initialized the terminal. Additionally, I created an empty list to store the events, but I'm unsure which events need to be included. Also not sure if how to go about it

I would greatly appreciate your assistance in guiding me on how to proceed with this issue and how I can achieve an optimal solution.

**Comment by Julow** [comment]
Hi @Dezzy12, sorry for the slow reply.

The cram tests can only call executables (not functions) so we need to create one.
For this, we need to create a new directory, let say `test/cram`. (Make sure to pull the latest main branch)

Setting up the dune file might be a bit tricky, so take example on the one in Odoc: https://github.com/ocaml/odoc/blob/master/test/xref2/dune
We need something similar to the first 3 stanzas:
- `(executable ...)` defines an executable, its name and dependency. Note that we also need a `<name>.ml` file.
- `(env ...)` make the executable accessible to the next stanza.
- `(cram ...)` enable cram tests and add executables as its dependencies.

The rest in this example is not needed. The `.ml` file would look a lot like `bin/main.ml`.

Here's the documentation for cram tests in Dune: https://dune.readthedocs.io/en/stable/reference/cram.html

A good foundation would be to have all of this setup with an executable that just prints "Hello World" and do not call the library yet.

Then, with the executable and the cram test setup, you'd be able to focus on the library side.

**Comment by yokurang** [comment]
Issue finished
